### ISSUE TITLE
Move / copy documentation from READMEs into the documentation project

### ISSUE THREAD

**Issue by warriordog** [warriordog/ActivityPubSharp#138]
Readme files should be left with a useful summary and links to the documentation. The "Types" readme has a particularly large amount of content to move.

**Comment by Raithlin** [comment]
Are you expecting a complete rewrite, or (certainly to start with) a basic "copy the existing readme.md to github.io and leave a summary in the readme.md"? 
Following on that question, would the documentation retain the existing links to code? I've glanced at the current documentation which looks to be auto-generated. It would be immensely helpful if you had an example that we could start from.

**Comment by warriordog** [comment]
@Raithlin My thinking was like this:
To start with, just copy the existing readme files into the documentation. Then replace the original files with a small summary + link to the original. For the main repository-level readme, I'd prefer that it be left mostly unchanged, just make sure that all of the info is copied into the main docs somewhere. Then remove any minor details that don't need to be in the main file.

Does that sounds reasonable?

**Comment by Raithlin** [comment]
Let me see what I can do with that. I'll respond properly if/when I need more clarity.

**Comment by warriordog** [comment]
@Raithlin thank you so much!

**Comment by Raithlin** [comment]
Do you want to replace the existing documentation, append or insert the readme above the existing text?

**Comment by warriordog** [comment]
@Raithlin I was thinking of adding a subsection in the documentation somewhere, with package-specific info. Then the existing documentation could be inserted as new files there.

**Comment by warriordog** [comment]
This might help: https://warriordog.github.io/ActivityPubSharp/Contributing/contributing_to_documentation.html

It's a little out of date and is missing a lot of info, though.

**Comment by Raithlin** [comment]
I read that last night. 🙏  Right, if you can create a subsection I can get started (we can always rename it later, right?)

Perhaps this should go under Dev Resources - or its own subsection perhaps.

**Comment by Raithlin** [comment]
@warriordog Am I correct in thinking this belongs in Dev Resources? If I put it in API it'll be overwritten if I understand this right. 

I'm looking at something like this:

| Overview
-| ActivityPub.Client
--| Overview
-| ActivityPub.Common
--| Overview


etc. Are you happy with this arrangement for the moment?

**Comment by Raithlin** [comment]
Apologies - I'm getting to know DocFX. As I read further I find more ways to get things done.

**Comment by warriordog** [comment]
@Raithlin that structure works 👍

**Comment by Raithlin** [comment]
@warriordog I'm pre-empting a question I had the other day on another project: How do we submit PRs? Create a branch on your project, or fork and submit that way?
