### ISSUE TITLE
NuGet snapshot workflow fails exactly 10% of the time

### ISSUE THREAD

**Issue by warriordog** [warriordog/ActivityPubSharp#168]
For some reason, MSBuild blows up if the millisecond component of the snapshot version starts with a zero. This happens exactly 10% of the time, so we can probably just remove that component entirely.

```log
C:\Program Files\dotnet\sdk\7.0.404\NuGet.targets(158,5): error : '0.1.0-snapshot.2023-12-27.05-23-38.039' is not a valid version string. (Parameter 'value') [D:\a\ActivityPubSharp\ActivityPubSharp\ActivityPubSharp.sln]
```

Look at any of the recently failed pipeline runs for more details.

**Comment by flensrocker** [comment]
Educated guess: octal numbers start with a zero and the 9 is not a valid digit...
