### ISSUE TITLE
Convert JsonLDContextObject, JsonLDTerm, and JsonLDExpandedTerm to record classes

### ISSUE THREAD

**Issue by warriordog** [warriordog/ActivityPubSharp#37]
This should allow us to remove all the Equals() stuff. Need unit tests to ensure everything behaves the same. Also check if records support inheritance - that's important for JsonLDTerm and JsonLDExpandedTerm.

**Comment by CreggHancock** [comment]
Is the goal for this to be able to compare both objects by property value equality instead of by reference? I was planning on picking this one up, but saw that the Equals() stuff were using ReferenceEquals() so just want to make sure the plan was to switch to value comparisons since that's what record will do by default (for value types).

**Comment by warriordog** [comment]
@CreggHancock Yes, that's the intent. These are meant to be immutable and unique, so giving them value equality allows them to be used with HashSet and Dictionary without any duplication. Thanks for confirming!

**Comment by CreggHancock** [comment]
Yep totally makes sense! I still feel like we'll run into an issue with the [dictionary](https://github.com/warriordog/ActivityPubSharp/blob/e11a8e231d54a2f8099567823caebbeb8c743283/ActivityPub.Types/Util/JsonLDContextObject.cs#L45C67-L45C67) in JsonLDContextObject with it being a reference type. Some quick investigation shows it's trying to compare equality with reference type properties by reference even after JsonLDContextObject has been converted to a record.

I have found some possible solutions to this, like rolling out your own dictionary class that handles value comparison for equality. An example is in this [gist](https://gist.github.com/ryanholden8/5602a6cc6decebb5bb35e21aa37efa67). If that's a route you'd like to go down I'm happy to implement that.

**Comment by warriordog** [comment]
@CreggHancock sorry, I totally missed your last comment! Thank you for bringing that up. Let me do some thinking and I'll get back to you.

**Comment by CreggHancock** [comment]
@warriordog No problem! And sure. I'll try doing some more research as well to see if there are any better alternatives. The gist seems decent but it would add some bloat 😅

**Comment by warriordog** [comment]
@CreggHancock Do other collections, like `List<T>`, work easier? I just realized that the list of contexts is small enough that we can probably do a naive linear search with no noticeable performance impact.

**Comment by warriordog** [comment]
@CreggHancock Related, we could probably just implement a basic linked list for this. I've never seen a real-world object with more than 5 context entries.

**Comment by warriordog** [comment]
@CreggHancock we should only need to use it in the context types, right? We don't want _everything_ to be value-typed.

**Comment by CreggHancock** [comment]
Sure! The intention would be to use it for comparing these record types. I just meant it _could_ be used throughout the project if we need value based comparisons. If we don't want that I can just implement it as an internal class though

**Comment by warriordog** [comment]
@CreggHancock do you think we would need this anywhere else? I can't think of any other place that needs to compare a list by value equality.

**Comment by warriordog** [comment]
@CreggHancock I think the best option to to implement a custom collection. For safety, I think it should *not* be generic and instead be hardcoded to only the exact case we need (`IReadOnlyDictionary<string, JsonLDTerm>`). Otherwise, someone could accidentally use it with a mutable type. What do you think?

**Comment by CreggHancock** [comment]
Sure that should work!

**Comment by warriordog** [comment]
@CreggHancock just to clarify - did you want to pick up this work, or should I go ahead and do it?

**Comment by CreggHancock** [comment]
I am happy to take this but I may not have the time to get to it until next week. If you have the bandwidth to take it before then then you can feel free to!

**Comment by warriordog** [comment]
@CreggHancock sounds good! I may do it before then depending on my schedule this week. I'm getting very close to completing Project 1 (AS extensions) and this is a part of that.

**Comment by warriordog** [comment]
Done. This should be the last thing before merging extensions support
