### ISSUE TITLE
JsonLdSerializer: add all overloads from JsonSerializer

### ISSUE THREAD

**Issue by warriordog** [warriordog/ActivityPubSharp#60]
The signature should be exactly the same except the options parameter is removed and populated from the instance property instead. Its meant to be a thin utility wrapper that simply provides that one property.

**Comment by pedro-henrique-araujo** [comment]
Hey @warriordog how is it going? I'm a C# developer and I'm eager to help, But think I need more overall understanding of this project. I've read the readme and so far I know that this is a wrapper for a network protocol. I'd like to see it working but I'm not sure what test case I can do. Let me know if you're available to help.

**Comment by warriordog** [comment]
@pedro-henrique-araujo hello! I'd be happy to explain things, but lets do it in a discussion thread instead of an active issue. I've written up a brief overview of project goals and expected usage - feel free to reply there with any questions! https://github.com/warriordog/ActivityPubSharp/discussions/63

**Comment by pedro-henrique-araujo** [comment]
@warriordog awesome I'll take a look and continue there

**Comment by warriordog** [comment]
Done in #163
