### ISSUE TITLE
ASCollection: add property to get first-populated of (Current, First, Last)

### ISSUE THREAD

**Issue by warriordog** [warriordog/ActivityPubSharp#62]
This is a gap in our API / null safety. If IsPaged is true, then *at least* one of these must be true. We can define that meta property and link its nullability to IsPaged. This will provide a slightly more ergonomic API over paged collections.

**Comment by CreggHancock** [comment]
I'll claim this one! If I'm reading this correctly, this is just an easy way to use a getter to get paged collection pages, falling back until you find a non-null value with a priority of First => Current => Last. Is that right?

**Comment by warriordog** [comment]
@CreggHancock Thanks! And yes that's correct, although I wonder if the order should instead be Current => First => Last. What do you think?

**Comment by CreggHancock** [comment]
I am still pretty naive with the AP spec and kinda learning as I go so I'm not quite sure, but that was going to be my next question. It seems like it'd be more relevant for the user to get the Current at a higher priority.

**Comment by warriordog** [comment]
@CreggHancock yeah that sounds like a better approach. I'll update the issue.

**Comment by warriordog** [comment]
@CreggHancock just checking in - are you still working on this? need any help?
