### ISSUE TITLE
Rename `[ASTypeKey]` attribute

### ISSUE THREAD

**Issue by warriordog** [warriordog/ActivityPubSharp#70]
Rename the attribute to something else. Reasoning:
1. It defines an ActivityPub type, not Activity*Streams*.
2. May be used to track metadata at a future point (such as #39 and #36).

Proposed name: `APTypeAttribute` / `[APType]`

**Comment by viktoriussuwandi** [comment]
Hi [warriordog](https://github.com/warriordog),
May I try to help on this issue ?

I need some informations (just to make sure) :
Do you need to rename `ASTypeKey` to `APTypeAttribute ` on the entire files on this project ? 
I have seen your project and `ASTypeKey` exist on several files, may I divide the solutions into several PR for these changes, just to easily maintenance in the future.

Once you answer, I will start to working on this

**Comment by warriordog** [comment]
@viktoriussuwandi Yes, that would be wonderful! Ideally, the type `ASTypeKeyAttribute` will be renamed to `APTypeAttribute` and the actual attributes will be changed from `[ASTypeKey(SomeType)]` to `[APType(SomeType)]`.

This will need to be changed in all the files. I'd prefer that you make all the changes in one PR, otherwise the non-changed types will be broken. You can, if you want, create a draft PR and then add commits one-at-a-time. I wont merge it until everything is done, and you can work at your own pace.

Thanks in advance for your help!

**Comment by viktoriussuwandi** [comment]
Ok I will, thanks @warriordog!

**Comment by warriordog** [comment]
@viktoriussuwandi no problem, and thank *you*!
